services:
  php-apache-otel:
    container_name: php-apache-apache-ecs
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile.local
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network-php-ecs
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    container_name: php-apache-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: 
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network-php-ecs
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres_userweb -d postgres_db"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  app-network-php-ecs:
    driver: bridge

volumes:
  postgres-data:
