services:
  php-apache-otel:
    container_name: php-apache-apache-ecs
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile.local
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network-php-ecs
networks:
  app-network-php-ecs:
    driver: bridge
  