name: dev - deploy aws ECS

on:
  push:
    branches:
      - master

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  ECS_CLUSTER: ${{ secrets.ECS_CLUSTER }}
  ECS_SERVICE: ${{ secrets.ECS_SERVICE }}
  ECS_TASK_DEFINITION: ${{ secrets.ECS_TASK_DEFINITION }}
  ECS_TASK_FAMILY: ${{ secrets.ECS_TASK_FAMILY }}

jobs:
  deploy:
    name: Deploy para AWS ECS
    runs-on: ubuntu-latest

    steps:
      - name: 🔽 Checkout do código
        uses: actions/checkout@v3
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: 🔐 Login no Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: 🏗 Construir e pushar imagem para o ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest ./src
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          
      - name: 📥 Obter a Task Definition atual do ECS
        run: |
          aws ecs describe-task-definition --task-definition $ECS_TASK_FAMILY \
            --query taskDefinition > task-definition.json

      - name: 🔄 Atualizar Task Definition com nova imagem
        run: |
          NEW_IMAGE="${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest"
          jq --arg IMAGE "$NEW_IMAGE" \
            '.containerDefinitions[0].image = $IMAGE' \
            task-definition.json > new-task-definition.json
            
      - name: 📜 Criar nova Task Definition no ECS
        id: register-task-def
        run: |
          TASK_REVISION=$(aws ecs register-task-definition --cli-input-json file://new-task-definition.json \
            --query 'taskDefinition.taskDefinitionArn' --output text)
          echo "TASK_REVISION=$TASK_REVISION" >> $GITHUB_ENV

      - name: 🚀 Atualizar serviço ECS
        run: |
          aws ecs update-service --cluster $ECS_CLUSTER \
            --service $ECS_SERVICE --task-definition $TASK_REVISION
